In [1]:
import numpy as np

In [2]:
m1 = np.array([[1,3,2],[4,5,3]])
m1

array([[1, 3, 2],
       [4, 5, 3]])

In [3]:
m1.T

array([[1, 4],
       [3, 5],
       [2, 3]])

In [4]:
s = np.array([4])
s.T

array([4])

In [5]:
v = np.array([1,3,4])
v.T

array([1, 3, 4])

In [6]:
v_r = v.reshape(1,3)
v_r

array([[1, 3, 4]])

In [7]:
v_r.T

array([[1],
       [3],
       [4]])

## Multiplication

In [8]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [10]:
# Dot product
np.dot(x,y)

32

In [11]:
x

array([1, 2, 3])

In [12]:
np.dot(2,x)

array([2, 4, 6])

In [13]:
2*x

array([2, 4, 6])

In [14]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
3*A

array([[ 3,  6,  9],
       [12, 15, 18]])

In [16]:
B = np.array([[7,8], [9,10], [11,12]])
B

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])